apiVersion: v1
kind: Secret
metadata:
  name: taskflow-secrets
  namespace: taskflow
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: rootpassword
  MYSQL_USER: taskflow
  MYSQL_PASSWORD: taskflow123
  JWT_SECRET: mySuperSecretKeyThatShouldBeAtLeast256BitsLongForHS256Algorithm
