apiVersion: v1
kind: ConfigMap
metadata:
  name: taskflow-config
  namespace: taskflow
data:
  MYSQL_DATABASE: taskflow
  SPRING_PROFILES_ACTIVE: dev
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/taskflow?useSSL=false&serverTimezone=Asia/Bangkok&allowPublicKeyRetrieval=true
  SPRING_DATA_REDIS_HOST: redis
  SPRING_DATA_REDIS_PORT: "6379"
